export default {
  audio: {
    'bannerhit3.wav': require(`./assets/audio/bannerhit3.wav`),
    'bannerhit4.mp3': require(`./assets/audio/bannerhit4.mp3`),
    'buck1.wav': require(`./assets/audio/buck1.wav`),
    'buck10.wav': require(`./assets/audio/buck10.wav`),
    'buck11.wav': require(`./assets/audio/buck11.wav`),
    'buck12.wav': require(`./assets/audio/buck12.wav`),
    'buck2.wav': require(`./assets/audio/buck2.wav`),
    'buck3.wav': require(`./assets/audio/buck3.wav`),
    'buck4.wav': require(`./assets/audio/buck4.wav`),
    'buck5.wav': require(`./assets/audio/buck5.wav`),
    'buck6.wav': require(`./assets/audio/buck6.wav`),
    'buck7.wav': require(`./assets/audio/buck7.wav`),
    'buck8.wav': require(`./assets/audio/buck8.wav`),
    'buck9.wav': require(`./assets/audio/buck9.wav`),
    'car_engine_loop_deep.wav': require(`./assets/audio/car_engine_loop_deep.wav`),
    'car_explosion.mp3': require(`./assets/audio/car_explosion.mp3`),
    'car_explosion2.mp3': require(`./assets/audio/car_explosion2.mp3`),
    'car_hit.mp3': require(`./assets/audio/car_hit.mp3`),
    'car_horn.wav': require(`./assets/audio/car_horn.wav`),
    'car_squish3.wav': require(`./assets/audio/car_squish3.wav`),
    'chicken_death.wav': require(`./assets/audio/chicken_death.wav`),
    'chicken_death2.wav': require(`./assets/audio/chicken_death2.wav`),
    'earn_points.mp3': require(`./assets/audio/earn_points.mp3`),
    'explosion_temp.mp3': require(`./assets/audio/explosion_temp.mp3`),
    'frog1.wav': require(`./assets/audio/frog1.wav`),
    'get_coin_73.mp3': require(`./assets/audio/get_coin_73.mp3`),
    'get_coin_75.wav': require(`./assets/audio/get_coin_75.wav`),
    'pig1.mp3': require(`./assets/audio/pig1.mp3`),
    'pig2.mp3': require(`./assets/audio/pig2.mp3`),
    'pig3.mp3': require(`./assets/audio/pig3.mp3`),
    'pig4.mp3': require(`./assets/audio/pig4.mp3`),
    'pig5.mp3': require(`./assets/audio/pig5.mp3`),
    'pig6.mp3': require(`./assets/audio/pig6.mp3`),
    'pig7.mp3': require(`./assets/audio/pig7.mp3`),
    'pop_1.wav': require(`./assets/audio/pop_1.wav`),
    'pop_2.wav': require(`./assets/audio/pop_2.wav`),
    'train_alarm.wav': require(`./assets/audio/train_alarm.wav`),
    'train_pass_no_horn.wav': require(`./assets/audio/train_pass_no_horn.wav`),
    'train_pass_shorter.wav': require(`./assets/audio/train_pass_shorter.wav`),
    'trainsplat.wav': require(`./assets/audio/trainsplat.wav`),
    'watersplashlow.mp3': require(`./assets/audio/watersplashlow.mp3`),
  },
  fonts: {
    'retro.ttf': require(`./assets/fonts/retro.ttf`),
  },
  icons: {
    'android.png': require(`./assets/icons/android.png`),
    'expo.png': require(`./assets/icons/expo.png`),
    'ios.png': require(`./assets/icons/ios.png`),
    'splash.png': require(`./assets/icons/splash.png`),
  },
  images: {
    'title.png': require(`./assets/images/title.png`),
    buttons: {
      'alerts.png': require(`./assets/images/buttons/alerts.png`),
      'back.png': require(`./assets/images/buttons/back.png`),
      'camera.png': require(`./assets/images/buttons/camera.png`),
      'character.png': require(`./assets/images/buttons/character.png`),
      'conserve_battery.png': require(`./assets/images/buttons/conserve_battery.png`),
      'controller.png': require(`./assets/images/buttons/controller.png`),
      'credits.png': require(`./assets/images/buttons/credits.png`),
      'facebook.png': require(`./assets/images/buttons/facebook.png`),
      'hand.png': require(`./assets/images/buttons/hand.png`),
      'language.png': require(`./assets/images/buttons/language.png`),
      'long_play.png': require(`./assets/images/buttons/long_play.png`),
      'mail.png': require(`./assets/images/buttons/mail.png`),
      'menu.png': require(`./assets/images/buttons/menu.png`),
      'mute.png': require(`./assets/images/buttons/mute.png`),
      'purchase.png': require(`./assets/images/buttons/purchase.png`),
      'random.png': require(`./assets/images/buttons/random.png`),
      'rank.png': require(`./assets/images/buttons/rank.png`),
      'settings.png': require(`./assets/images/buttons/settings.png`),
      'shadows.png': require(`./assets/images/buttons/shadows.png`),
      'share.png': require(`./assets/images/buttons/share.png`),
      'shop.png': require(`./assets/images/buttons/shop.png`),
      'social.png': require(`./assets/images/buttons/social.png`),
      'video_ads.png': require(`./assets/images/buttons/video_ads.png`),
    },
    hand: {
      '0.png': require(`./assets/images/hand/0.png`),
      '1.png': require(`./assets/images/hand/1.png`),
    },
  },
  models: {
    collectables: {
      yellow: {
        '0.mtl': require(`./assets/models/collectables/yellow/0.mtl`),
        '0.obj': require(`./assets/models/collectables/yellow/0.obj`),
        '0.png': require(`./assets/models/collectables/yellow/0.png`),
      },
      red: {
        '0.mtl': require(`./assets/models/collectables/red/0.mtl`),
        '0.obj': require(`./assets/models/collectables/red/0.obj`),
        '0.png': require(`./assets/models/collectables/red/0.png`),
      },
    },
    characters: {
      bacon: {
        '0.mtl': require(`./assets/models/characters/bacon/0.mtl`),
        '0.obj': require(`./assets/models/characters/bacon/0.obj`),
        '0.png': require(`./assets/models/characters/bacon/0.png`),
      },
      baller: {
        '0.mtl': require(`./assets/models/characters/baller/0.mtl`),
        '0.obj': require(`./assets/models/characters/baller/0.obj`),
        '0.png': require(`./assets/models/characters/baller/0.png`),
        'ball.mtl': require(`./assets/models/characters/baller/ball.mtl`),
        'ball.obj': require(`./assets/models/characters/baller/ball.obj`),
        'ball.png': require(`./assets/models/characters/baller/ball.png`),
        'bounce.mtl': require(`./assets/models/characters/baller/bounce.mtl`),
        'bounce.obj': require(`./assets/models/characters/baller/bounce.obj`),
        'bounce.png': require(`./assets/models/characters/baller/bounce.png`),
      },
      big_fat_pig: {
        '0.mtl': require(`./assets/models/characters/big_fat_pig/0.mtl`),
        '0.obj': require(`./assets/models/characters/big_fat_pig/0.obj`),
        '0.png': require(`./assets/models/characters/big_fat_pig/0.png`),
      },
      brent: {
        '0.mtl': require(`./assets/models/characters/brent/0.mtl`),
        '0.obj': require(`./assets/models/characters/brent/0.obj`),
        '0.png': require(`./assets/models/characters/brent/0.png`),
      },
      brown_bunny: {
        '0.mtl': require(`./assets/models/characters/brown_bunny/0.mtl`),
        '0.obj': require(`./assets/models/characters/brown_bunny/0.obj`),
        '0.png': require(`./assets/models/characters/brown_bunny/0.png`),
      },
      celebrity: {
        '0.mtl': require(`./assets/models/characters/celebrity/0.mtl`),
        '0.obj': require(`./assets/models/characters/celebrity/0.obj`),
        '0.png': require(`./assets/models/characters/celebrity/0.png`),
      },
      android_robot: {
        '0.mtl': require(`./assets/models/characters/android_robot/0.mtl`),
        '0.obj': require(`./assets/models/characters/android_robot/0.obj`),
        '0.png': require(`./assets/models/characters/android_robot/0.png`),
      },
      chicken: {
        '0.mtl': require(`./assets/models/characters/chicken/0.mtl`),
        '0.obj': require(`./assets/models/characters/chicken/0.obj`),
        '0.png': require(`./assets/models/characters/chicken/0.png`),
      },
      crazy_ol_ben: {
        '0.mtl': require(`./assets/models/characters/crazy_ol_ben/0.mtl`),
        '0.obj': require(`./assets/models/characters/crazy_ol_ben/0.obj`),
        '0.png': require(`./assets/models/characters/crazy_ol_ben/0.png`),
      },
      doge: {
        '0.mtl': require(`./assets/models/characters/doge/0.mtl`),
        '0.obj': require(`./assets/models/characters/doge/0.obj`),
        '0.png': require(`./assets/models/characters/doge/0.png`),
      },
      emo_goose: {
        '0.mtl': require(`./assets/models/characters/emo_goose/0.mtl`),
        '0.obj': require(`./assets/models/characters/emo_goose/0.obj`),
        '0.png': require(`./assets/models/characters/emo_goose/0.png`),
      },
      ghost: {
        '0.mtl': require(`./assets/models/characters/ghost/0.mtl`),
        '0.obj': require(`./assets/models/characters/ghost/0.obj`),
        '0.png': require(`./assets/models/characters/ghost/0.png`),
        'chains.mtl': require(`./assets/models/characters/ghost/chains.mtl`),
        'chains.obj': require(`./assets/models/characters/ghost/chains.obj`),
        'chains.png': require(`./assets/models/characters/ghost/chains.png`),
        'ghost.mtl': require(`./assets/models/characters/ghost/ghost.mtl`),
        'ghost.obj': require(`./assets/models/characters/ghost/ghost.obj`),
        'ghost.png': require(`./assets/models/characters/ghost/ghost.png`),
      },
      floppy_fish: {
        '0.mtl': require(`./assets/models/characters/floppy_fish/0.mtl`),
        '0.obj': require(`./assets/models/characters/floppy_fish/0.obj`),
        '0.png': require(`./assets/models/characters/floppy_fish/0.png`),
      },
      hipster_whale: {
        '0.mtl': require(`./assets/models/characters/hipster_whale/0.mtl`),
        '0.obj': require(`./assets/models/characters/hipster_whale/0.obj`),
        '0.png': require(`./assets/models/characters/hipster_whale/0.png`),
      },
      ide: {
        '0.mtl': require(`./assets/models/characters/ide/0.mtl`),
        '0.obj': require(`./assets/models/characters/ide/0.obj`),
        '0.png': require(`./assets/models/characters/ide/0.png`),
      },
      kangaroo: {
        '0.mtl': require(`./assets/models/characters/kangaroo/0.mtl`),
        '0.obj': require(`./assets/models/characters/kangaroo/0.obj`),
        '0.png': require(`./assets/models/characters/kangaroo/0.png`),
      },
      kiwi: {
        '0.mtl': require(`./assets/models/characters/kiwi/0.mtl`),
        '0.obj': require(`./assets/models/characters/kiwi/0.obj`),
        '0.png': require(`./assets/models/characters/kiwi/0.png`),
      },
      mad_wizard: {
        '0.mtl': require(`./assets/models/characters/mad_wizard/0.mtl`),
        '0.obj': require(`./assets/models/characters/mad_wizard/0.obj`),
        '0.png': require(`./assets/models/characters/mad_wizard/0.png`),
      },
      mallard: {
        '0.mtl': require(`./assets/models/characters/mallard/0.mtl`),
        '0.obj': require(`./assets/models/characters/mallard/0.obj`),
        '0.png': require(`./assets/models/characters/mallard/0.png`),
      },
      nikki: {
        '0.mtl': require(`./assets/models/characters/nikki/0.mtl`),
        '0.obj': require(`./assets/models/characters/nikki/0.obj`),
        '0.png': require(`./assets/models/characters/nikki/0.png`),
      },
      penguin: {
        '0.mtl': require(`./assets/models/characters/penguin/0.mtl`),
        '0.obj': require(`./assets/models/characters/penguin/0.obj`),
        '0.png': require(`./assets/models/characters/penguin/0.png`),
      },
      pew_die_pug: {
        '0.mtl': require(`./assets/models/characters/pew_die_pug/0.mtl`),
        '0.obj': require(`./assets/models/characters/pew_die_pug/0.obj`),
        '0.png': require(`./assets/models/characters/pew_die_pug/0.png`),
      },
      platypus: {
        '0.mtl': require(`./assets/models/characters/platypus/0.mtl`),
        '0.obj': require(`./assets/models/characters/platypus/0.obj`),
        '0.png': require(`./assets/models/characters/platypus/0.png`),
      },
      poopy_pigeon: {
        '0.mtl': require(`./assets/models/characters/poopy_pigeon/0.mtl`),
        '0.obj': require(`./assets/models/characters/poopy_pigeon/0.obj`),
        '0.png': require(`./assets/models/characters/poopy_pigeon/0.png`),
      },
      rusty_robot: {
        '0.mtl': require(`./assets/models/characters/rusty_robot/0.mtl`),
        '0.obj': require(`./assets/models/characters/rusty_robot/0.obj`),
        '0.png': require(`./assets/models/characters/rusty_robot/0.png`),
      },
      specimen_115: {
        '0.mtl': require(`./assets/models/characters/specimen_115/0.mtl`),
        '0.obj': require(`./assets/models/characters/specimen_115/0.obj`),
        '0.png': require(`./assets/models/characters/specimen_115/0.png`),
      },
      the_dark_lord: {
        '0.mtl': require(`./assets/models/characters/the_dark_lord/0.mtl`),
        '0.obj': require(`./assets/models/characters/the_dark_lord/0.obj`),
        '0.png': require(`./assets/models/characters/the_dark_lord/0.png`),
      },
      tree_frog: {
        '0.mtl': require(`./assets/models/characters/tree_frog/0.mtl`),
        '0.obj': require(`./assets/models/characters/tree_frog/0.obj`),
        '0.png': require(`./assets/models/characters/tree_frog/0.png`),
      },
      vampire: {
        '0.mtl': require(`./assets/models/characters/vampire/0.mtl`),
        '0.obj': require(`./assets/models/characters/vampire/0.obj`),
        '0.png': require(`./assets/models/characters/vampire/0.png`),
      },
      zombie: {
        '0.mtl': require(`./assets/models/characters/zombie/0.mtl`),
        '0.obj': require(`./assets/models/characters/zombie/0.obj`),
        '0.png': require(`./assets/models/characters/zombie/0.png`),
        'body.mtl': require(`./assets/models/characters/zombie/body.mtl`),
        'body.obj': require(`./assets/models/characters/zombie/body.obj`),
        'body.png': require(`./assets/models/characters/zombie/body.png`),
        'head.mtl': require(`./assets/models/characters/zombie/head.mtl`),
        'head.obj': require(`./assets/models/characters/zombie/head.obj`),
        'head.png': require(`./assets/models/characters/zombie/head.png`),
      },
    },
    vehicles: {
      blue_car: {
        '0.mtl': require(`./assets/models/vehicles/blue_car/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/blue_car/0.obj`),
        '0.png': require(`./assets/models/vehicles/blue_car/0.png`),
      },
      blue_truck: {
        '0.mtl': require(`./assets/models/vehicles/blue_truck/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/blue_truck/0.obj`),
        '0.png': require(`./assets/models/vehicles/blue_truck/0.png`),
      },
      green_car: {
        '0.mtl': require(`./assets/models/vehicles/green_car/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/green_car/0.obj`),
        '0.png': require(`./assets/models/vehicles/green_car/0.png`),
      },
      orange_car: {
        '0.mtl': require(`./assets/models/vehicles/orange_car/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/orange_car/0.obj`),
        '0.png': require(`./assets/models/vehicles/orange_car/0.png`),
      },
      police_car: {
        '0.mtl': require(`./assets/models/vehicles/police_car/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/police_car/0.obj`),
        '0.png': require(`./assets/models/vehicles/police_car/0.png`),
      },
      purple_car: {
        '0.mtl': require(`./assets/models/vehicles/purple_car/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/purple_car/0.obj`),
        '0.png': require(`./assets/models/vehicles/purple_car/0.png`),
      },
      red_truck: {
        '0.mtl': require(`./assets/models/vehicles/red_truck/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/red_truck/0.obj`),
        '0.png': require(`./assets/models/vehicles/red_truck/0.png`),
      },
      taxi: {
        '0.mtl': require(`./assets/models/vehicles/taxi/0.mtl`),
        '0.obj': require(`./assets/models/vehicles/taxi/0.obj`),
        '0.png': require(`./assets/models/vehicles/taxi/0.png`),
      },
      train: {
        back: {
          '0.mtl': require(`./assets/models/vehicles/train/back/0.mtl`),
          '0.obj': require(`./assets/models/vehicles/train/back/0.obj`),
          '0.png': require(`./assets/models/vehicles/train/back/0.png`),
        },
        front: {
          '0.mtl': require(`./assets/models/vehicles/train/front/0.mtl`),
          '0.obj': require(`./assets/models/vehicles/train/front/0.obj`),
          '0.png': require(`./assets/models/vehicles/train/front/0.png`),
        },
        middle: {
          '0.mtl': require(`./assets/models/vehicles/train/middle/0.mtl`),
          '0.obj': require(`./assets/models/vehicles/train/middle/0.obj`),
          '0.png': require(`./assets/models/vehicles/train/middle/0.png`),
        },
      },
    },
    environment: {
      lily_pad: {
        '0.mtl': require(`./assets/models/environment/lily_pad/0.mtl`),
        '0.obj': require(`./assets/models/environment/lily_pad/0.obj`),
        '0.png': require(`./assets/models/environment/lily_pad/0.png`),
      },
      railroad: {
        '0.mtl': require(`./assets/models/environment/railroad/0.mtl`),
        '0.obj': require(`./assets/models/environment/railroad/0.obj`),
        '0.png': require(`./assets/models/environment/railroad/0.png`),
      },
      river: {
        '0.mtl': require(`./assets/models/environment/river/0.mtl`),
        '0.obj': require(`./assets/models/environment/river/0.obj`),
        '0.png': require(`./assets/models/environment/river/0.png`),
      },
      boulder: {
        '0': {
          '0.mtl': require(`./assets/models/environment/boulder/0/0.mtl`),
          '0.obj': require(`./assets/models/environment/boulder/0/0.obj`),
          '0.png': require(`./assets/models/environment/boulder/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/boulder/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/boulder/1/0.obj`),
          '0.png': require(`./assets/models/environment/boulder/1/0.png`),
        },
      },
      eagle: {
        '0': {
          '0.mtl': require(`./assets/models/environment/eagle/0/0.mtl`),
          '0.obj': require(`./assets/models/environment/eagle/0/0.obj`),
          '0.png': require(`./assets/models/environment/eagle/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/eagle/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/eagle/1/0.obj`),
          '0.png': require(`./assets/models/environment/eagle/1/0.png`),
        },
        '2': {
          '0.mtl': require(`./assets/models/environment/eagle/2/0.mtl`),
          '0.obj': require(`./assets/models/environment/eagle/2/0.obj`),
          '0.png': require(`./assets/models/environment/eagle/2/0.png`),
        },
      },
      grass: {
        '0': {
          '0.mtl': require(`./assets/models/environment/grass/0/0.mtl`),
          '0.obj': require(`./assets/models/environment/grass/0/0.obj`),
          '0.png': require(`./assets/models/environment/grass/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/grass/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/grass/1/0.obj`),
          '0.png': require(`./assets/models/environment/grass/1/0.png`),
        },
      },
      log: {
        '0': {
          '0.mtl': require(`./assets/models/environment/log/0/0.mtl`),
          '0.obj': require(`./assets/models/environment/log/0/0.obj`),
          '0.png': require(`./assets/models/environment/log/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/log/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/log/1/0.obj`),
          '0.png': require(`./assets/models/environment/log/1/0.png`),
        },
        '2': {
          '0.mtl': require(`./assets/models/environment/log/2/0.mtl`),
          '0.obj': require(`./assets/models/environment/log/2/0.obj`),
          '0.png': require(`./assets/models/environment/log/2/0.png`),
        },
        '3': {
          '0.mtl': require(`./assets/models/environment/log/3/0.mtl`),
          '0.obj': require(`./assets/models/environment/log/3/0.obj`),
          '0.png': require(`./assets/models/environment/log/3/0.png`),
        },
      },
      road: {
        '0': {
          '0.mtl': require(`./assets/models/environment/road/0/0.mtl`),
          '0.obj': require(`./assets/models/environment/road/0/0.obj`),
          '0.png': require(`./assets/models/environment/road/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/road/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/road/1/0.obj`),
          '0.png': require(`./assets/models/environment/road/1/0.png`),
        },
      },
      tree: {
        '0': {
          '0.obj': require(`./assets/models/environment/tree/0/0.obj`),
          '0.mtl': require(`./assets/models/environment/tree/0/0.mtl`),
          '0.png': require(`./assets/models/environment/tree/0/0.png`),
        },
        '1': {
          '0.mtl': require(`./assets/models/environment/tree/1/0.mtl`),
          '0.obj': require(`./assets/models/environment/tree/1/0.obj`),
          '0.png': require(`./assets/models/environment/tree/1/0.png`),
        },
        '2': {
          '0.mtl': require(`./assets/models/environment/tree/2/0.mtl`),
          '0.obj': require(`./assets/models/environment/tree/2/0.obj`),
          '0.png': require(`./assets/models/environment/tree/2/0.png`),
        },
        '3': {
          '0.mtl': require(`./assets/models/environment/tree/3/0.mtl`),
          '0.obj': require(`./assets/models/environment/tree/3/0.obj`),
          '0.png': require(`./assets/models/environment/tree/3/0.png`),
        },
      },
      bird: {
        idle: {
          '0': {
            '0.mtl': require(`./assets/models/environment/bird/idle/0/0.mtl`),
            '0.obj': require(`./assets/models/environment/bird/idle/0/0.obj`),
            '0.png': require(`./assets/models/environment/bird/idle/0/0.png`),
          },
          '1': {
            '0.mtl': require(`./assets/models/environment/bird/idle/1/0.mtl`),
            '0.obj': require(`./assets/models/environment/bird/idle/1/0.obj`),
            '0.png': require(`./assets/models/environment/bird/idle/1/0.png`),
          },
        },
        flying: {
          '0': {
            '0.mtl': require(`./assets/models/environment/bird/flying/0/0.mtl`),
            '0.obj': require(`./assets/models/environment/bird/flying/0/0.obj`),
            '0.png': require(`./assets/models/environment/bird/flying/0/0.png`),
          },
          '1': {
            '0.mtl': require(`./assets/models/environment/bird/flying/1/0.mtl`),
            '0.obj': require(`./assets/models/environment/bird/flying/1/0.obj`),
            '0.png': require(`./assets/models/environment/bird/flying/1/0.png`),
          },
          '2': {
            '0.mtl': require(`./assets/models/environment/bird/flying/2/0.mtl`),
            '0.obj': require(`./assets/models/environment/bird/flying/2/0.obj`),
            '0.png': require(`./assets/models/environment/bird/flying/2/0.png`),
          },
        },
      },
      train_light: {
        inactive: {
          '0.mtl': require(`./assets/models/environment/train_light/inactive/0.mtl`),
          '0.obj': require(`./assets/models/environment/train_light/inactive/0.obj`),
          '0.png': require(`./assets/models/environment/train_light/inactive/0.png`),
        },
        active: {
          '0': {
            '0.mtl': require(`./assets/models/environment/train_light/active/0/0.mtl`),
            '0.obj': require(`./assets/models/environment/train_light/active/0/0.obj`),
            '0.png': require(`./assets/models/environment/train_light/active/0/0.png`),
          },
          '1': {
            '0.mtl': require(`./assets/models/environment/train_light/active/1/0.mtl`),
            '0.obj': require(`./assets/models/environment/train_light/active/1/0.obj`),
            '0.png': require(`./assets/models/environment/train_light/active/1/0.png`),
          },
        },
      },
    },
  },
};
